# Generated by Django 4.2.7 on 2025-08-03 12:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('daily_signups', models.PositiveIntegerField(default=0)),
                ('total_signups', models.PositiveIntegerField(default=0)),
                ('unique_ips', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Waitlist Statistics',
                'verbose_name_plural': 'Waitlist Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text="User's email address", max_length=254, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address for rate limiting', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=64, null=True)),
                ('source', models.CharField(default='website', help_text='Source of the signup', max_length=50)),
                ('user_agent', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Waitlist Entry',
                'verbose_name_plural': 'Waitlist Entries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='waitlist_wa_email_0a1da6_idx'), models.Index(fields=['created_at'], name='waitlist_wa_created_5f5734_idx'), models.Index(fields=['ip_address'], name='waitlist_wa_ip_addr_d4f7f1_idx')],
            },
        ),
    ]
